//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsDemo.locatable_resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoIsDemo.locatable_resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WhoIs DEMO.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The channel does not exist it must be created..
        /// </summary>
        internal static string channel_not_exist {
            get {
                return ResourceManager.GetString("channel_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join channel: .
        /// </summary>
        internal static string channels {
            get {
                return ResourceManager.GetString("channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation Completed..
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Define configuration parameters and channels, take a video test, please. .
        /// </summary>
        internal static string configuration_empty {
            get {
                return ResourceManager.GetString("configuration_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete the database? The application will close..
        /// </summary>
        internal static string delete_database {
            get {
                return ResourceManager.GetString("delete_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The configuration directory es empty .
        /// </summary>
        internal static string directory_config_empty {
            get {
                return ResourceManager.GetString("directory_config_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in the task performed..
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files:.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The video address is incorrect..
        /// </summary>
        internal static string ip_video_empty {
            get {
                return ResourceManager.GetString("ip_video_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The library of recognition face can´t load..
        /// </summary>
        internal static string library_not_load {
            get {
                return ResourceManager.GetString("library_not_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The library is not loaded, please check..
        /// </summary>
        internal static string load_library {
            get {
                return ResourceManager.GetString("load_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low Score:.
        /// </summary>
        internal static string low_score {
            get {
                return ResourceManager.GetString("low_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video not loaded.
        /// </summary>
        internal static string pipe_not_loaded {
            get {
                return ResourceManager.GetString("pipe_not loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reloaded library.
        /// </summary>
        internal static string reload_library {
            get {
                return ResourceManager.GetString("reload_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeated:.
        /// </summary>
        internal static string repetead_user {
            get {
                return ResourceManager.GetString("repetead_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset application, please..
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data saved correctly.
        /// </summary>
        internal static string save_ok {
            get {
                return ResourceManager.GetString("save_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set pause channels..
        /// </summary>
        internal static string set_pause_channels {
            get {
                return ResourceManager.GetString("set_pause_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop Library..
        /// </summary>
        internal static string stop_library {
            get {
                return ResourceManager.GetString("stop_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type of video is incorrect..
        /// </summary>
        internal static string type_video_incorrect {
            get {
                return ResourceManager.GetString("type_video_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value key is empty.
        /// </summary>
        internal static string value_key_empty {
            get {
                return ResourceManager.GetString("value_key_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Key..
        /// </summary>
        internal static string verify_key {
            get {
                return ResourceManager.GetString("verify_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Channel not found..
        /// </summary>
        internal static string video_not_found {
            get {
                return ResourceManager.GetString("video_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The video is correct..
        /// </summary>
        internal static string video_ok {
            get {
                return ResourceManager.GetString("video_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The video must be disabled and library load..
        /// </summary>
        internal static string window_disabled {
            get {
                return ResourceManager.GetString("window_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Working....
        /// </summary>
        internal static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
    }
}
