//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsDemo.locatable_resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoIsDemo.locatable_resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhoIs DEMO.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed..
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define configuration parameters, please.
        /// </summary>
        internal static string configuration_empty {
            get {
                return ResourceManager.GetString("configuration_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the database? The application will close..
        /// </summary>
        internal static string delete_database {
            get {
                return ResourceManager.GetString("delete_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration directory es empty .
        /// </summary>
        internal static string directory_config_empty {
            get {
                return ResourceManager.GetString("directory_config_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the task performed..
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video address is empty..
        /// </summary>
        internal static string ip_video_empty {
            get {
                return ResourceManager.GetString("ip_video_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library is not loaded, please check..
        /// </summary>
        internal static string load_library {
            get {
                return ResourceManager.GetString("load_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Score:.
        /// </summary>
        internal static string low_score {
            get {
                return ResourceManager.GetString("low_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloaded library.
        /// </summary>
        internal static string reload_library {
            get {
                return ResourceManager.GetString("reload_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated:.
        /// </summary>
        internal static string repetead_user {
            get {
                return ResourceManager.GetString("repetead_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset application, please..
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Library..
        /// </summary>
        internal static string stop_library {
            get {
                return ResourceManager.GetString("stop_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of video is incorrect..
        /// </summary>
        internal static string type_video_incorrect {
            get {
                return ResourceManager.GetString("type_video_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value key is empty.
        /// </summary>
        internal static string value_key_empty {
            get {
                return ResourceManager.GetString("value_key_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Key..
        /// </summary>
        internal static string verify_key {
            get {
                return ResourceManager.GetString("verify_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
    }
}
