//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsDemo.locatable_resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoIsDemo.locatable_resources.StringResource_es", typeof(StringResource_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhoIs DEMO.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación completada..
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defina los parámetros de configuración, por favor..
        /// </summary>
        internal static string configuration_empty {
            get {
                return ResourceManager.GetString("configuration_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de borrar la base de datos? La aplicación se cerrará..
        /// </summary>
        internal static string delete_database {
            get {
                return ResourceManager.GetString("delete_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El directorio de configuración está vacio..
        /// </summary>
        internal static string directory_config_empty {
            get {
                return ResourceManager.GetString("directory_config_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la tarea realizada..
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos:.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de video está vacia..
        /// </summary>
        internal static string ip_video_empty {
            get {
                return ResourceManager.GetString("ip_video_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La librería no está cargada, verifique por favor..
        /// </summary>
        internal static string load_library {
            get {
                return ResourceManager.GetString("load_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score bajo:.
        /// </summary>
        internal static string low_score {
            get {
                return ResourceManager.GetString("low_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librería recargada..
        /// </summary>
        internal static string reload_library {
            get {
                return ResourceManager.GetString("reload_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetidos:.
        /// </summary>
        internal static string repetead_user {
            get {
                return ResourceManager.GetString("repetead_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinice la aplicación, por favor..
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librería detenida..
        /// </summary>
        internal static string stop_library {
            get {
                return ResourceManager.GetString("stop_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de video es incorrecto..
        /// </summary>
        internal static string type_video_incorrect {
            get {
                return ResourceManager.GetString("type_video_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de la llave está vacio..
        /// </summary>
        internal static string value_key_empty {
            get {
                return ResourceManager.GetString("value_key_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique la llave, por favor..
        /// </summary>
        internal static string verify_key {
            get {
                return ResourceManager.GetString("verify_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere....
        /// </summary>
        internal static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
    }
}
