//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoIsDemo.locatable_resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource_es() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhoIsDemo.locatable_resources.StringResource_es", typeof(StringResource_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WhoIs DEMO.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El canal no existe y debe ser creado..
        /// </summary>
        internal static string channel_not_exist {
            get {
                return ResourceManager.GetString("channel_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor apague el canal..
        /// </summary>
        internal static string channel_off {
            get {
                return ResourceManager.GetString("channel_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canales adscritos:  .
        /// </summary>
        internal static string channels {
            get {
                return ResourceManager.GetString("channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación completada..
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defina los parámetros de configuración y el orden de los canales , realice la verificación de video, por favor..
        /// </summary>
        internal static string configuration_empty {
            get {
                return ResourceManager.GetString("configuration_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de entrada en canal:.
        /// </summary>
        internal static string control_entry {
            get {
                return ResourceManager.GetString("control_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro de borrar la base de datos? La aplicación se cerrará..
        /// </summary>
        internal static string delete_database {
            get {
                return ResourceManager.GetString("delete_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El directorio de configuración está vacio..
        /// </summary>
        internal static string directory_config_empty {
            get {
                return ResourceManager.GetString("directory_config_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos vacios..
        /// </summary>
        internal static string empty_data {
            get {
                return ResourceManager.GetString("empty_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la tarea realizada..
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos:.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de video es incorrecta..
        /// </summary>
        internal static string ip_video_empty {
            get {
                return ResourceManager.GetString("ip_video_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La libreria de reconocimiento facial no pudo cargar..
        /// </summary>
        internal static string library_not_load {
            get {
                return ResourceManager.GetString("library_not_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La librería no está cargada, verifique por favor..
        /// </summary>
        internal static string load_library {
            get {
                return ResourceManager.GetString("load_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score bajo:.
        /// </summary>
        internal static string low_score {
            get {
                return ResourceManager.GetString("low_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número menor o mayor que el rango..
        /// </summary>
        internal static string message_range {
            get {
                return ResourceManager.GetString("message_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número esta fuera de rango..
        /// </summary>
        internal static string number_out_range {
            get {
                return ResourceManager.GetString("number_out_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los canales de videos no están cargados..
        /// </summary>
        internal static string pipe_not_loaded {
            get {
                return ResourceManager.GetString("pipe_not loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Librería recargada..
        /// </summary>
        internal static string reload_library {
            get {
                return ResourceManager.GetString("reload_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetidos:.
        /// </summary>
        internal static string repetead_user {
            get {
                return ResourceManager.GetString("repetead_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinice la aplicación, por favor..
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados correctamente..
        /// </summary>
        internal static string save_ok {
            get {
                return ResourceManager.GetString("save_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coloque en pausa los canales..
        /// </summary>
        internal static string set_pause_channels {
            get {
                return ResourceManager.GetString("set_pause_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Librería detenida..
        /// </summary>
        internal static string stop_library {
            get {
                return ResourceManager.GetString("stop_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de video es incorrecto..
        /// </summary>
        internal static string type_video_incorrect {
            get {
                return ResourceManager.GetString("type_video_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enrolar usuario en canal:.
        /// </summary>
        internal static string user_enroll {
            get {
                return ResourceManager.GetString("user_enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de la llave está vacio..
        /// </summary>
        internal static string value_key_empty {
            get {
                return ResourceManager.GetString("value_key_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique la llave, por favor..
        /// </summary>
        internal static string verify_key {
            get {
                return ResourceManager.GetString("verify_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario no tiene ningún canal adjunto..
        /// </summary>
        internal static string video_not_found {
            get {
                return ResourceManager.GetString("video_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El video es correcto..
        /// </summary>
        internal static string video_ok {
            get {
                return ResourceManager.GetString("video_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El video debe estar desactivado y la libreria cargada..
        /// </summary>
        internal static string window_disabled {
            get {
                return ResourceManager.GetString("window_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las ventanas no están cargadas..
        /// </summary>
        internal static string windows_not_loaded {
            get {
                return ResourceManager.GetString("windows_not_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere....
        /// </summary>
        internal static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
    }
}
